# Generated by Django 5.0.4 on 2024-04-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
